# Generated by Django 4.2.7 on 2025-10-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='marks',
        ),
    ]
