# Generated by Django 4.2.7 on 2025-10-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0002_remove_option_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='has_correct_answers',
            field=models.BooleanField(default=False, help_text='Check this if questions in this category have correct answers.'),
        ),
        migrations.AlterField(
            model_name='subjectiveoption',
            name='text',
            field=models.CharField(help_text="e.g., 'Strongly Agree', 'Neutral'", max_length=255),
        ),
        migrations.AlterField(
            model_name='subjectiveoptiontemplate',
            name='name',
            field=models.CharField(help_text="e.g., '5-Point Likert Scale'", max_length=100, unique=True),
        ),
    ]
