# Generated by Django 4.2.7 on 2025-10-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0004_alter_category_has_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='has_correct_answers',
            field=models.BooleanField(default=False, help_text='Check this if questions in this category have correct answers.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subjective_option_template',
            field=models.ForeignKey(blank=True, help_text='Choose a template of options for this section if it is subjective.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey_api.subjectiveoptiontemplate'),
        ),
        migrations.AlterField(
            model_name='subjectiveoption',
            name='text',
            field=models.CharField(help_text="e.g., 'Strongly Agree', 'Neutral'", max_length=255),
        ),
        migrations.AlterField(
            model_name='subjectiveoptiontemplate',
            name='name',
            field=models.CharField(help_text="e.g., '5-Point Likert Scale'", max_length=100, unique=True),
        ),
    ]
