# Generated by Django 4.2.7 on 2025-10-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0005_alter_category_has_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subjective_option_template',
            field=models.ForeignKey(blank=True, help_text="Choose a template of options for this section if it's subjective.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey_api.subjectiveoptiontemplate'),
        ),
    ]
