# Generated by Django 4.2.7 on 2025-10-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0006_alter_section_subjective_option_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentsectionresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='has_correct_answers',
            field=models.BooleanField(default=False, help_text='Check if questions in this category have correct answers.'),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='subjective_option_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey_api.subjectiveoptiontemplate'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectiveoption',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'student_id'], name='survey_api__college_91a5f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('college', 'student_id'), name='unique_college_studentid'),
        ),
        migrations.AddConstraint(
            model_name='studentresponse',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='unique_student_question_response'),
        ),
        migrations.AddConstraint(
            model_name='studentsectionresult',
            constraint=models.UniqueConstraint(fields=('student', 'section'), name='unique_student_section_result'),
        ),
    ]
