# Generated by Django 4.2.7 on 2025-10-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0007_alter_student_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
    ]
