# Generated by Django 4.2.7 on 2025-11-20 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0009_collegeadminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
